######################## Paths to scripts ######################## 

c3poa_path: "/home/vstorozhuk/Mandalorion_notes/C3POa_new/C3POa"
mandalorion_path: "/home/vstorozhuk/Mandalorion_notes/Mandalorion"
sqanti3_path: "~/Mandalorion_notes/sqanti3/release_sqanti3"

######################## Input / Output Dirs  ######################## 

input_dir: "/work/vstorozhuk/data/iso_pipeline/pipeline_inputs"
output_dir: "/work/vstorozhuk/data/iso_pipeline/pipeline_outputs"

######################## References ########################

references:
  GRCh38:
    reference_fasta: "/work/vstorozhuk/data/reference/Homo_sapiens.GRCh38.dna_sm.toplevel.fa"
    reference_gtf:   "/work/vstorozhuk/data/reference/Homo_sapiens.GRCh38.114.gtf"

  PanTro3:
    reference_fasta: "/work/vstorozhuk/data/reference/GCF_028858775.2_NHGRI_mPanTro3-v2.0_pri_genomic.fna"
    reference_gtf:   "/work/vstorozhuk/data/reference/GCF_028858775.2_NHGRI_mPanTro3-v2.0_pri_genomic_standardized.gtf"

  Mmul10:
    reference_fasta: "/work/vstorozhuk/data/reference/GCF_003339765.1_Mmul_10_genomic.fna"
    reference_gtf:   "/work/vstorozhuk/data/reference/GCF_003339765.1_Mmul_10_genomic_standardized.gtf"
    
  CalJac1:
    reference_fasta: "/work/vstorozhuk/data/reference/GCF_011100555.1_mCalJa1.2.pat.X_genomic.fna"
    reference_gtf:   "/work/vstorozhuk/data/reference/GCF_011100555.1_mCalJa1.2.pat.X_genomic.standardized.gtf"

######################## C3POa / trimming ########################

splint: "/work/vstorozhuk/data/iso_pipeline/pipeline_inputs/splint.fasta"
adapters: "/work/vstorozhuk/data/iso_pipeline/pipeline_inputs/PNAS2018_adapters.fasta"
trim: "28,2"

######################## Samples ######################## 

samples:
  Barcode01:
    reference: "GRCh38"
  Barcode02:
    reference: "PanTro3"
  Barcode03:
    reference: "Mmul10"
  Barcode04:
    reference: "CalJac1"

######################## RnaSeq fofn ######################## 
 
rna_fofn:
   Barcode02: "/work/vstorozhuk/data/rna_seq_for_alignment/PanTro3/PanTro.fofn"
   Barcode03: "/work/vstorozhuk/data/rna_seq_for_alignment/Mmul10/MMul.fofn"
   Barcode04: "/work/vstorozhuk/data/rna_seq_for_alignment/CalJac4/CalJac.fofn"
   
  
  
######################### CAGE ######################## 

cage_peaks:
   Barcode02: "/work/vstorozhuk/data/CAGE/rheMac8_cage_peaks_in_PanTro3_coords.bed"
   Barcode03: "/work/vstorozhuk/data/CAGE/rheMac8_cage_peaks_in_RheMac10_RefSeq_coords.bed"
   Barcode04: "/work/vstorozhuk/data/CAGE/rheMac8_cage_peaks_in_caljac1.2_coords.bed"
    
